disabled_rules:
- leading_whitespace
- trailing_whitespace
- line_length
- force_try
included:
excluded:
- Pods
- FruitSchool/Supporting Files/AppDelegate.swift

cyclomatic_complexity: 20
identifier_name:
    excluded:
    - id
    - _id
